ueman/feedback

CHANGELOG.md
lib/src/better_feedback.dart
lib/src/feedback_widget.dart
pubspec.yaml
test/feedback_test.dart

Exposes the pixelRatio parameter, so that the user can influence the quality and size of the screenshot. Default stays the same (3.0).
The quality and size depends on the app. For an upload to online storage the high resolution results in too large files (2MB+). This would mean that a conversion would be needed, which is costly on the server. Instead it makes more sense to allow to take the screenshot at a lower resolution right away.
Integration Test

Add option for changing the quality and size of the screenshot

---

lib/src/feedback_bottom_sheet.dart

By default, pressing 'Enter', will now dismiss the keyboard.
Better user experience.
Tested on real iOS Device (iPhone SE 2020)

Enter-Button dismisses keyboard

---

lib/src/controls_column.dart
lib/src/theme/feedback_theme.dart

Uses `disabledColor` to make the currently selected navigate/draw button highlighted with a color specified in `FeedbackTheme`.
See: https://github.com/ueman/feedback/issues/75
Ran the example app (this is a super small/safe change so hopefully that's sufficient?)
1. Review, merge and publish!
2. Consider extending the feedback theme to allow users to override this color directly.

Make Currently Selected Column Control Use accentColor

---

lib/src/feedback_bottom_sheet.dart
test/feedback_test.dart
test/test_app.dart

Got distracted trying to fix the `feedback callback gets called` test while working on #78. Finally fixed it and figured I'd put the fix in a PR to go in before #78 given that the latter is huge and controversial and thus may not even go in.
There were three primary aspects to fixing the test:
1. It needed to be restructured so that it fails if the callback isn't called-previously it'd only fail if the callback WAS called, but with a null screenshot.
2. Screenshot was creating some weird asynchronous dependency that I couldn't understand. But whatever it was it was causing `await controller.capture...` to hang in the testing environment so I swapped it out with the mock screenshot controller.
3. The test app was accidentally always passing a null `onFeedback` to `MyTestPage`.
Test was …

Fixed 'feedback callback gets called' Test

---

CHANGELOG.md
example/pubspec.lock
lib/src/feedback_widget.dart
lib/src/painter.dart
pubspec.yaml
test/feedback_test.dart

Implements https://github.com/ueman/feedback/issues/116
The behavior of the back button in navigation mode remains the same.
In drawing mode, it will first undo the last drawings.
If no drawing is left, the feedback view is closed.
I wanted to implement the listener to the back button with WillPopScope, but this requires a Scaffold.
I was unable to find any other way to listen to the back button without using a new dependency.
However [this dependency](https://pub.dev/packages/back_button_interceptor) is well-maintained, compatible to the same scope as this package currently is and light-weight.
See https://github.com/ueman/feedback/issues/116
Android Emulator, Test cases
None

Add intelligent handling of the back button

---

.devcontainer/devcontainer.json
CONTRIBUTING.md

This adds support for GitHub codespaces using the `cirrusci:flutter` docker image.
This eases contributing to this library. Contributors do not need to setup a whole flutter toolchain + emulators locally.
I created this PR from the codespace created by this PR.
- [  ] I added tests to verify changes
Test it for yourself (Open a new code space, copy over the `devcontainer.json` file, rebuild the code space, follow the instructions in `CONTRIBUTING.md`)

Added devcontainer including documentation

---

feedback/lib/src/l18n/translation.dart

The locale debugPrint says `englisch` although it should be `english`.
thanks @calcitem for finding this
We just saw the german english string in our app and pinned it down to this package
compile, get an unsupported locale, see the log :upside_down_face: 
<s>I added tests to verify changes </s> N.A.

Fix typo in debugPrint

---

feedback/lib/src/feedback_widget.dart
feedback/test/feedback_test.dart

This change keeps the initial model after we re-open the feedback widget.
When we select an initial mode, let say `Navigation`, every time we open the feedback widget that mode should be selected but it wasn't working in that way, the last mode selected remains even after we re-open the widget. 
- A new unit test was added in `feedback_test`. 
- If you want to reproduce the issue: set the mode NAVIGATION, open the feedback widget, select DRAW, close and open again. You will see the DRAW remains active.

Keep the initial mode after we re-open the widget

---

feedback/CHANGELOG.md
feedback/lib/src/feedback_widget.dart
feedback/pubspec.yaml

Removes the explicit `meta` dependency declaration
Removes `meta` explicit dependency to avoid future version conflicts (it was already outdated)
https://github.com/flutter/flutter/issues/95658
`meta` is still used as a transitive dependency and the tags used also come from the Flutter framework

Remove `meta` dependency

---

feedback/lib/src/l18n/translation.dart

This way, when inheriting from the class, one can simply set
_supportedLocales without having to override load().
Should theoretically make implementing translations easier and with less boilerplate code.
Remove the load() function from https://github.com/ueman/feedback/issues/160#issuecomment-1018361157
I didn't :)

translation: Load localization dynamically

---

feedback/lib/src/better_feedback.dart

Changed the `OnSubmit` `typedef` to return a `Future<void>` instead of just `void`.
I'm using a custom feedback sheet via `BetterFeedback.feedbackBuilder` and would like to be able to display a loading indicator while awaiting submission to complete. Otherwise, the UI sits on the feedback screen with no visible activity until submission completes. To the user, this may feel like the app has frozen momentarily.
1. My feedback widget is stateful and holds a `bool isSubmitting`. `OnSubmit` is passed to my feedback widget from `FeedbackBuilder`. A "Submit" button is displayed at the bottom of the sheet, which changes to a loading indicator when `isSubmitting` is `true`. It contains an `onPressed` similar to the following:
```dart
onPressed: () async {
setState(() => isSubmitting = true); …
```

allow awaiting submission

---

feedback/lib/src/feedback_bottom_sheet.dart
feedback/pubspec.yaml

The new flutter release now supports snapping sheets!
This PR just enables snapping. I'll create a larger PR later that updates feedback to use the new sheet controller argument.
Tested by manually playing with it in my own app.

enable snap for realsies this time

---

feedback/lib/src/utilities/feedback_app.dart

Before wrapping the app widget in a new `MediaQuery` it's checking for an existing one. If there's already a `MediaQuery' Widget, it doesn't replace the old one.
I don't add the `BetterFeedback` widget above the `MaterialApp`, instead in the `builder` from `MaterialApp`, because I'm using [DevicePreview](https://pub.dev/packages/device_preview) and [ResponsiveFramework](https://pub.dev/packages/responsive_framework). They have to be above the `BetterFeedback` widget and manipulate the `MediaQuery`. So I changed this package to use the existing `MediaQuery` widget, if any.
I have tested the changes manually in my own project.

fix: don't replace existing MediaQuery widget

---

feedback/example/android/build.gradle
feedback/lib/src/feedback_bottom_sheet.dart
feedback/lib/src/feedback_controller.dart
feedback/lib/src/feedback_widget.dart

This PR exposes a `DraggableScrollableController` from `FeedbackController`.
This was a PR I intended to do a long time ago, but it was blocking on a PR landing in `flutter/flutter` and that took so long that I forgot to get back to this ):
I have a handful of TODOs in other places that this PR unblocks, but I figured I'd do those in a follow up PR as they're much fussier and harder to land.
This PR allows users of `BetterFeedback` to listen to the state of the feedback sheet and manually manipulate it. This is useful for things like:
1. Manipulating the sheet from within your custom sheet content
2. Driving animations from within your sheet
1. Remove the public drag handle widget and automatically embed it in the user's sheet gated behind a bool in the feedback theme
2. Replace …

adds an exposed sheet contorller to the better feedback controller

---

feedback/lib/src/feedback_builder/string_feedback.dart
feedback/lib/src/theme/feedback_theme.dart

Added option to enable users to provide custom text input styles.

bottom sheet with text input style option enabled

---

feedback/lib/src/l18n/translation.dart

add Japanese localization

---

feedback/lib/src/l18n/translation.dart

Adding default portuguese (pt) locale
Currently there isn't a FeedbackLocalizations for the Portuguese language
Running the example app with locale setted as "pt"
Add it as a default localization

feat: ✨ portuguese default locale

---

feedback/README.md

A link in the README of the feedback package was broken, linking to a non-existent GitHub page (see screenshot below).
The link was: https://github.com/ueman/feedback/blob/master/example/lib/main.dart
And the correct one would be: https://github.com/ueman/feedback/blob/master/feedback/example/lib/main.dart
Manually

fix: broken link to sample app in README

---

feedback/lib/src/l18n/translation.dart

Only translation file is affected with this change, it adds Spanish language as supported by delegate with the default translation.
This should close request #283 to add Spanish support on default feedback
- Modifying the example locale to 'es'.
- Testing with a physical device
- [  ] I added tests to verify changes
- [  ] I updated the docs if needed
- [  ] All tests passing

feat(translation): add Spanish support in localization delegate

---

feedback/lib/src/l18n/translation.dart

I have added Farsi as a localization.
Persian speakers who use Farsi can now utilize the "fa" localization.
I made a minor change to mirror your code and tested the syntax of my translation using your sample.

Farsi has been added as a localization

---

feedback/example/lib/custom_feedback.dart
feedback/example/lib/main.dart
feedback/lib/src/feedback_bottom_sheet.dart
feedback/lib/src/feedback_widget.dart

When a dialog is showed, and the back button in Android is pressed, the dialog don't pop, instead the `back` action is executen in the background screen
The error was given because the use of an `navigation` widget in the widget tree prevent the back action from actually poping the dialog (btw, I'm not 100% sure why this bug is reproduced, but I know that with this change it get solved)
Before: 
```dart
return Navigator(
onGenerateRoute: (_) {
return MaterialPageRoute<void>(
builder: (context) {
return Theme(...);
}
),
},
);
```
After: 
```dart
return Overlay(
initialEntries: [
OverlayEntry(
builder: (context) => Theme(...),
),
],
);
```
This PR solve the `Dialog not popping` issue
This issue is reported in:
- [Issue 194](https://github.com/ueman/feedback/issues/194)
- [Issue …

Fix: broken pop dialog

---

feedback/lib/src/theme/feedback_theme.dart
feedback/test/theme/feedback_theme_test.dart

Adds a `copyWith` method to `FeedbackThemeData`. Also adds `brightness` as a settable property.
This fixes issue #311.
By calling `copyWith` in the example and seeing its results.

Add a copy with method to FeedbackThemeData

---

README.md

I created a variant to upload feedback as github issues, storing images in a firebase storage bucket
I only added the link to the package in readme : https://pub.dev/packages/feedback_github
The github repo : https://github.com/tempo-riz/feedback_github

Add link to feedback_github package

---

feedback/lib/src/feedback_widget.dart

This hotfix addresses a Focus exception that occurs on the Web platform when a user submits feedback and then hides/restores the browser window. The issue stems from a focus context being accessed before it's properly attached.
This fix wraps focus-related logic to prevent execution if the context is not available, avoiding a crash caused by premature access to focus traversal state. This issue was reproducible only on the Web after toggling browser window visibility post-feedback submission.
Sample of crash:  
`Exception:
DartError: Assertion failed: file:///home/user/snap/flutter/common/flutter/packages/flutter/lib/src/widgets/focus_manager.dart:854:7
context != null
"Tried to get the bounds of a focus node that didn't have its context set yet.\nThe context needs to be set before trying …

fix(web): prevent Focus exception after feedback submission and window restore

---

feedback/lib/src/l18n/translation.dart

The `feedback` package did not support Bangla, which is needed for apps like Charge.AI serving Bangladeshi users.
* Manually tested in a demo Flutter app using `BetterFeedback` widget.
* Switched device/app locale to `bn` and verified translated text.
---
* Consider adding support for other RTL languages like Urdu.
* Improve UI adaptability for translated text with longer phrases.

Add Bangla (bn) Localization Support
